### ISSUE TITLE
CRF_accuracy 和 自己设置的评价指标，差别很大。

### ISSUE THREAD

**Issue by brealisty** [AidenHuen/BERT-BiLSTM-CRF#2]
400个样本（为了验证代码正确性，测试集也用这部分样本），用crf自带的acc，基本不会超过0.6，用test中F1值，可以达到很高，crf_acc源代码没细看，test中的F1的公式感觉应该还是比较靠谱。大神，有遇到过这样的问题吗？

**Comment by AidenHuen** [comment]
我这个项目有自带demo的数据集，你可以跑一下，我记得我跑的时候是没问题。还有，这个项目是比较就已前的，用的BERT并不能fine-tune，效果可能没有BERT的极致好，如果你有需要的，我可以修改一下项目。

**Comment by brealisty** [comment]
> 我这个项目有自带demo的数据集，你可以跑一下，我记得我跑的时候是没问题。还有，这个项目是比较就已前的，用的BERT并不能fine-tune，效果可能没有BERT的极致好，如果你有需要的，我可以修改一下项目。

嘿嘿，谢谢，不用了，校验过预测的结果·，应该是crf的acc有一些问题吧。整体效果还是·很好的。
